hidden_act: 'gelu'
loss_type: 'CE'
plm_suffix: pth #feat3CLS
img_suffix: pth
text_size: 768
image_size: 1000
plm_text_size: 768
plm_image_size: 1000

seed: 2024
n_layers: 2
n_heads: 2
initializer_range: 0.02
layer_norm_eps: 1e-12

hidden_size: 256
inner_size: 256
hidden_dropout_prob: 0.5
attn_dropout_prob: 0.5
learning_rate: 0.001
item_dropout: 0.5
train_batch_size: 1024
lora_rank: 4
lamba: 0.01
alpha: 1.0
gpu_id: 0
temperature: 0.05
stage: stage1

